name: Publish Snapshot to NPM Registry

on:
  release:
    types: [published]

jobs:
  build-and-publish-snapshot:
    runs-on: macos-latest
    if: contains(github.event.release.tag_name, 'snapshot')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ vars.PNPM_7_VERSION }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Test package
        run: pnpm test

      - name: Set version to snapshot
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\/snapshot\///')
          pnpm version --no-git-tag-version "0.0.0-snapshot.${TAG_NAME}"

      - name: Publish snapshot package
        run: pnpm publish --tag snapshot --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SHINED_NPM_PUBLISH_TOKEN }}
